unit Aurelius.Sql.MSSQL;

{$I Aurelius.inc}

interface

uses
  DB,
  Aurelius.Sql.AnsiSqlGenerator,
  Aurelius.Sql.BaseTypes,
  Aurelius.Sql.Commands,
  Aurelius.Sql.Interfaces,
  Aurelius.Sql.Register;

type
  TMSSQLSQLGenerator = class(TAnsiSQLGenerator)
  protected
    function GetMaxConstraintNameLength: Integer; override;
    function FieldTypeToSQL(FieldDef: TSQLFieldDefinition): string; override;
    function GetSqlLiteral(AValue: Variant; AType: TFieldType): string; override;
    function GetGeneratorName: string; override;
    function GetSqlDialect: string; override;
    function GetSupportedFeatures: TDBFeatures; override;
    function GenerateGetLastInsertId(SQLField: TSQLField): string; override;
    function GenerateDropField(Command: TDropFieldCommand): string; override;
    function GenerateLimitedSelect(SelectSql: TSelectSql; Command: TSelectCommand): string; override;
    function GetSupportedFieldTypes: TFieldTypeSet; override;
  end;

implementation

uses
  Variants, SysUtils;

{ TMSSQLSQLGenerator }

function TMSSQLSQLGenerator.FieldTypeToSQL(
  FieldDef: TSQLFieldDefinition): string;
begin
  Result := NumericTypeToSQL(FieldDef);
  if Result <> '' then
    Exit;

  case FieldDef.FieldType of
    ftByte:
      Result := 'TINYINT';
    ftShortint:
      Result := 'TINYINT';
    ftLargeint:
      Result := 'BIGINT';

    ftDate:
      Result := 'DATETIME';
    ftTime:
      Result := 'TIME';
    ftDateTime:
      Result := 'DATETIME';

    ftMemo:
      Result := 'VARCHAR(MAX)';
    ftWideMemo:
      Result := 'NVARCHAR(MAX)';
    ftBlob:
      Result := 'VARBINARY(MAX)';
    ftGuid:
      Result := 'UNIQUEIDENTIFIER';
  else
    result := inherited FieldTypeToSQL(FieldDef);
  end;

  if FieldDef.AutoGenerated then
    Result := Result + ' IDENTITY(1,1)';
end;

function TMSSQLSQLGenerator.GenerateDropField(
  Command: TDropFieldCommand): string;
begin
  result := InternalGenerateDropField(Command, True);
end;

function TMSSQLSQLGenerator.GenerateGetLastInsertId(SQLField: TSQLField): string;
begin
  Result := 'SELECT CAST(IDENT_CURRENT('+QuotedStr(SQLField.Table.Name)+') AS INT)';
end;

function TMSSQLSQLGenerator.GenerateLimitedSelect(SelectSql: TSelectSql;
  Command: TSelectCommand): string;

  function GenerateLimitedSelectWithOffset: string;
  var
    RowNum: string;
    p: integer;
    SubSql: string;
    RowCondition: string;
  begin
    // Build the rownum column
    if SelectSql.OrderClause <> '' then
      RowNum := Format('ROW_NUMBER() OVER(%s) AS rownum, ', [SelectSql.OrderClause])
    else
      RowNum := 'ROW_NUMBER() OVER(ORDER BY CURRENT_TIMESTAMP) AS rownum, ';;

    // Insert the rownum column in the select statement
    p := Pos('SELECT', UpperCase(SelectSql.SelectClause));
    Assert(p > 0, 'SELECT word not found in SQL. Cannot generate limited select');
    p := p + Length('SELECT');

    // Build the regular sql with the new added rownum column and without order clause
    SelectSql.SelectClause := 'SELECT ' + RowNum + Copy(SelectSql.SelectClause, p, MaxInt);
    SelectSql.OrderClause := '';
    SubSql := GenerateRegularSelect(SelectSql);

    // Build the filter condition for rows to be retrieved
    if Command.HasFirstRow and Command.HasMaxRows then
      RowCondition := Format('rownum BETWEEN %d AND %d', [Command.FirstRow + 1, Command.LastRow + 1])
    else
    if Command.HasFirstRow then
      RowCondition := Format('rownum >= %d', [Command.FirstRow + 1])
    else
      RowCondition := Format('rownum <= %d', [Command.LastRow + 1]);

    Result := 'SELECT * FROM ( '#13#10 +
      SubSql + ') as tempset '#13#10 +
      'WHERE ' + RowCondition;
  end;

  function GenerateLimitedSelectWithTop: string;
  var
    p: integer;
    TopStr: string;
  begin
    Result := GenerateRegularSelect(SelectSql);
    p := Pos('SELECT', UpperCase(Result));
    Assert(p > 0, 'SELECT word not found in SQL. Cannot generate limited select');
    p := p + Length('SELECT');

    TopStr := TopStr + Format('TOP %d ', [Command.MaxRows]);
    Result := 'SELECT ' + TopStr + Copy(Result, p, MaxInt);
  end;

begin
  if Command.HasFirstRow then
    Result := GenerateLimitedSelectWithOffset
  else
    Result := GenerateLimitedSelectWithTop;
end;

function TMSSQLSQLGenerator.GetSqlDialect: string;
begin
  Result := 'MSSQL';
end;

function TMSSQLSQLGenerator.GetGeneratorName: string;
begin
  Result := 'MSSQL SQL Generator';
end;

function TMSSQLSQLGenerator.GetMaxConstraintNameLength: Integer;
begin
  Result := 128; //MSSQL 2008
end;

function TMSSQLSQLGenerator.GetSqlLiteral(AValue: Variant;
  AType: TFieldType): string;
begin
  Result := inherited GetSqlLiteral(AValue, AType);
  case AType of
    ftDate:
      Result := Format('CAST(''%s'' AS DATETIME)',
        [FormatDateTime('yyyy-mm-dd ', VarToDateTime(AValue))]);
    ftTime:
      Result := Format('CAST(''%s'' AS DATETIME)',
        [FormatDateTime('hh:nn:ss', VarToDateTime(AValue))]);
    ftDateTime,ftTimeStamp:
      Result := Format('CAST(''%s'' AS DATETIME)',
        [FormatDateTime('yyyy-mm-dd hh:nn:ss', VarToDateTime(AValue))]);
  end;
end;

function TMSSQLSQLGenerator.GetSupportedFeatures: TDBFeatures;
begin
  Result := AllDBFeatures - [TDBFeature.Sequences];
end;

function TMSSQLSQLGenerator.GetSupportedFieldTypes: TFieldTypeSet;
begin
  Result := inherited GetSupportedFieldTypes + [ftGuid];
end;

initialization
  TSQLGeneratorRegister.GetInstance.RegisterGenerator(TMSSQLSQLGenerator.Create);

end.
